tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  external_code_coverage: true
    timeout: 600

checks:
    php:
        code_rating: true
        duplication: true
        coding_standard:
            name: Magento