language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.6
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.6.2.0
  global:
  - secure: dRsyqZoE77xvReDFaVv6LgIU2zqIJZo7/Gey2sZOG77oUiPv6mXX1avEIaFcxXVDVoZ+PpW2AmxJk0LBDvGiFRRkxL6oRNkH19a/4VSyEs03j/yveXpgJFXZZFUtCDGYgVSKYaSbqTGVX73Lb4531ZFB/s7aQJlxkblYP4gqdZc=
  - secure: amieteq+tjtcH793tI9diTs/2OCgEE00FY8dAiFDR3jVUFSWXpptt1PDnTVf6+sCKKoCFSaMvfz8p+FLy2+cCDhfu79R9fdyE6BMNA4N3CN2x5r1qRwS37juvkpMic287veqB5qH3pX4JrpbYhYi6bkz0SdnB+ANoz+vpTWybo0=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/testing/setup.sh
  | bash
notifications:
  slack:
    secure: JfKv4qNBfFM2tJ3kZeonFdRgF52OH00kflsUR0XhQ6IHHujA5XKHUfPcvmuJSqQnEP+5PI2jP9U5sb9Wow+mLWVacCnif6CwfYViObYS3BsUD7emIkK7zeYfd5Umz77LQAB6Zy2vORGPdyQ/EdKG0nuobvmXTr3VwgHkKvKenKk=
