language: php

php:
  - 5.3
  - 5.4
  - 5.5

sudo: false

env:
  - MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65
  - MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66
  - MAGENTO_VERSION="magento-ce-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66
  - MAGENTO_VERSION="magento-ce-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66
  - MAGENTO_VERSION="magento-ce-1.8.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66
  # Do not download sample data of 1.9 -> The file is too big
  - MAGENTO_VERSION="magento-ce-1.9.0.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66
  - MAGENTO_VERSION="magento-ce-1.9.1.0" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

matrix:
  fast_finish: true
  exclude:
    # Newer Magento versions uses newer PHP versions
    - php: 5.3
      env: MAGENTO_VERSION="magento-ce-1.9.0.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

    - php: 5.3
      env: MAGENTO_VERSION="magento-ce-1.9.1.0" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

    # Old Magneto Versions are not officially supported to run with PHP 5.5
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65

    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66

    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66

    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - export N98_MAGERUN_TEST_MAGENTO_ROOT="./${MAGENTO_VERSION}"
  - bin/n98-magerun install --magentoVersionByName="${MAGENTO_VERSION}" --installationFolder="./${MAGENTO_VERSION}" --dbHost=localhost --dbUser=root --dbPass='' --dbName="magento_travis" --installSampleData=${INSTALL_SAMPLE_DATA} --useDefaultConfigParams=yes --baseUrl="http://travis.magento.local/"
  - git clone git://github.com/EcomDev/MageCI.git ./mageci/
  - ./mageci/bin/mage-ci install magento $MAGENTO_VERSION magento_test -c -t -r http://mage-ci.ecomdev.org
  - git clone git://github.com/EcomDev/EcomDev_PHPUnit.git -b dev ./phpunit/
  - CURR_DIR=$(pwd)
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -O ./mageci/bin/modman
  - chmod +x ./mageci/bin/modman
  - ./mageci/bin/mage-ci install-module $MAGENTO_VERSION $CURR_DIR/phpunit
  - ./mageci/bin/mage-ci install-module $MAGENTO_VERSION $CURR_DIR
  - cd $MAGENTO_VERSION

script:
  - ../vendor/bin/phpunit --group Aoe_Backup